version: '3'
services:

  web:
    build:
      dockerfile: Dockerfile.dev
      context: ./web
    ports:
      - '3000:3000'
      - '3001:3001'
    volumes:
      - /app/node_modules
      - ./web:/app
      
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./api
    volumes:
      - /app/node_modules
      - ./api:/app

